@Greenhouse.Runtime_HostAddress = http://127.0.0.1:5150

GET {{Greenhouse.Runtime_HostAddress}}/api/setup/status
Accept: application/json

###

GET {{Greenhouse.Runtime_HostAddress}}/api/setup/main-config
Accept: application/json

###
